import type { SceneDefinition, ScenarioVariant, Evidence } from '../../contract'
import { wildlife } from './wildlife-content'
import { incidentTime as T } from './incident-motion'
const observed=(source:string,detail:string):Evidence=>({kind:'observed',source,detail}),correlation=(source:string,detail:string):Evidence=>({kind:'correlation',source,detail}),response=(source:string,detail:string):Evidence=>({kind:'response',source,detail}),uncertain=(detail:string):Evidence=>({kind:'uncertainty',source:'Limits of this illustration',detail})
const incident:ScenarioVariant={
 id:'intrusion',label:'Perimeter intrusion',role:'primary',duration:T.end,
 poster:'/worlds/private-estate/intrusion-poster.webp',posterAlt:'Illustrative perimeter intrusion at a woodland estate: an anonymous person crosses the lower stone boundary while the occupied residence and guarded inner approach remain visible.',
 lesson:'Protection is a sequence: observe the boundary crossing, corroborate it, secure the occupied threshold and send a person to check. The fictional intruder’s retreat is scripted; the sensors do not establish identity or compel an outcome.',
 establishing:{title:'An occupied home, two boundaries',body:'A resident moves beside the warm room. An unarmed guard is at the service shelter; the operator has a separate terrace console. The low stone perimeter and the inner stair gate protect different parts of this fictional home.'},
 cameras:[
  {at:0,position:[-17,8.5,23],target:[-2,1.8,4],mobilePosition:[-12,8,24],mobileTarget:[-2,1.8,4.5],fov:46,easing:'smoother'},
  {at:T.detect,cut:true,position:[-9,3.7,12.5],target:[-4.4,1.2,8.5],mobilePosition:[-8.4,3.5,12.8],mobileTarget:[-4.4,1.2,8.5],fov:48},
  {at:14.9,position:[-8.4,3.8,12.2],target:[-4.4,1.2,8.4],mobilePosition:[-8.4,3.5,12.8],mobileTarget:[-4.4,1.2,8.5],fov:48},
  {at:T.verify,cut:true,position:[-1.8,5.3,15],target:[-2.3,1.8,5.8],mobilePosition:[-1.8,5.4,14.5],mobileTarget:[-2.3,1.9,5.8],fov:50},
  {at:22.9,position:[-1.8,5.3,15],target:[-2.3,1.8,5.8],mobilePosition:[-1.8,5.4,14.5],mobileTarget:[-2.3,1.9,5.8],fov:50},
  {at:T.correlate,cut:true,position:[-5,5.3,14],target:[-.5,1.7,4.5],mobilePosition:[-3,5,13],mobileTarget:[.6,1.85,4.5],fov:46},
  {at:T.decide,cut:true,position:[-3.2,3.7,9],target:[1.65,1.9,2.05],mobilePosition:[-3.8,3.6,7],mobileTarget:[1.3,2.4,1.3],fov:46},
  {at:35.8,position:[-3.2,3.7,9],target:[1.65,1.9,2.05],mobilePosition:[-3.8,3.6,7],mobileTarget:[1.3,2.4,1.3],fov:46},
  {at:36,cut:true,position:[7.8,4.3,9.4],target:[3.55,1.5,1.9],mobilePosition:[7,4.1,9.3],mobileTarget:[3.65,1.15,2.2],fov:48},
  {at:T.secured,cut:true,position:[-1,5.8,12],target:[2.4,1.4,4],mobilePosition:[-.3,5,11.5],mobileTarget:[2.4,1.5,4.3],fov:48},
  {at:T.standoff,cut:true,position:[8.5,4.2,11],target:[2.6,1.3,4.8],mobilePosition:[7.5,3.9,11],mobileTarget:[2.6,1.3,4.8],fov:50},
  {at:48,position:[8.5,4.2,11],target:[2.6,1.3,4.8],mobilePosition:[7.5,3.9,11],mobileTarget:[2.6,1.3,4.8],fov:50},
  {at:56.9,position:[-9,5,14],target:[-3,1.3,7.5],mobilePosition:[-8,4.3,14],mobileTarget:[-3.5,1.4,7.6],fov:48},
  {at:T.exitCross,cut:true,position:[-8.8,3.5,12.4],target:[-4.4,1.3,8.5],mobilePosition:[-8.4,3.5,12.8],mobileTarget:[-4.4,1.3,8.5],fov:48},
  {at:65.9,position:[-8.8,3.5,12.4],target:[-4.4,1.3,8.5],mobilePosition:[-8.4,3.5,12.8],mobileTarget:[-4.4,1.3,8.5],fov:48},
  {at:T.outside,cut:true,position:[-12,7,18],target:[-3,1.3,7],mobilePosition:[-11,6.5,18],mobileTarget:[-3,1.3,7],fov:48},
  {at:T.inspected,cut:true,position:[-9,4,4.5],target:[-4.4,1.2,8.7],mobilePosition:[-8,3.4,4.5],mobileTarget:[-4.4,1.3,8.7],fov:50},
  {at:T.end,position:[-14,7.5,20],target:[-1.5,1.7,5],mobilePosition:[-11,7,19],mobileTarget:[-2,1.8,5.8],fov:48},
 ],
 beats:[
  {id:'detect',at:T.detect,title:'A deliberate crossing of the stone perimeter',body:'The rust-clothed figure is the authored intruder in this red-team scenario. They put both hands on the coping, step onto the low wall and land inside. The fixed camera observes the exposed crossing; it does not infer intent from clothing.',evidence:[observed('Garden camera','A person approaches and crosses the visible stone boundary.'),uncertain('The adversarial role is fictional ground truth, not a sensor classification.')],subevents:[{id:'coping-contact',at:9,title:'Hands and feet on the boundary',body:'Both hands brace on the coping while the first foot is supported on top and the other remains outside. The perimeter zone indicator records the crossing area.',evidence:[observed('Perimeter zone','A local boundary-zone event accompanies the supported crossing.')]}]},
  {id:'verify',at:T.verify,title:'Two views corroborate one person inside',body:'The person has landed inside and walks toward the occupied terrace. The garden camera supplies shape and direction; the distinct terrace thermal contributes a labelled illustrative warm silhouette. No temperature or identity is assigned.',evidence:[observed('Garden camera','A human figure moves from the crossed wall toward the house.'),observed('Terrace thermal','Illustrative thermal-style view of the same person in the authored overlap; no temperatures.'),uncertain('Vegetation ends the depicted coverage. A hidden route is not a verified track.')]},
  {id:'correlate',at:T.correlate,title:'The crossing becomes a local operator alert',body:'Proposed on-site correlation joins the camera passage, warm silhouette and perimeter-zone event. Under the illustrated preauthorized policy, the path lights come on and the operator’s console displays the linked observations.',evidence:[correlation('Proposed local correlation','Camera + thermal + boundary-zone event form one proposed incident.'),response('Preauthorized path lighting','The four garden luminaires activate; the console alert becomes visible.')]},
  {id:'decide',at:T.decide,title:'Protect the occupied threshold; send a person',body:'The operator reviews the three observations. The resident is still beside the open doorway; the inner gate is open and the guard remains at the shelter. The decision below authorizes the protective response.',evidence:[observed('Local operator','The linked alert is present at the modeled console.'),uncertain('Securing the threshold and sending the guard are proposed actions until the authored decision continues.')],action:'Secure the inner terrace and send the guard to observe'},
  {id:'respond',at:T.respond,title:'A resident clears the doorway',body:'After the human decision, the resident steps inside and away from the doorway. The operator reaches the modeled console control. Once the threshold is clear, the room shutter and inner stair gate close; the unarmed guard uses the protected service path.',evidence:[response('Human-authorized sequence','Resident clearance, console action, closure and guard observation follow the decision.')],subevents:[
   {id:'inner-held',at:T.secured,title:'The inner threshold is held',body:'The room shutter and stair gate are fully closed. The resident is clear of their swept paths. The garden path remains lit as the guard approaches behind the fixed service railing.',evidence:[observed('Inner protection','Both mechanisms visibly reach their closed stops; the occupied room remains behind the shutter.'),response('Guard route','The guard stays on the home side of the service railing.')]},
   {id:'warning',at:45,title:'An unarmed warning at a standoff',body:'The intruder reaches the held stair gate. The guard stops on the protected service path and raises an open hand. They remain separated; there is no contact or arrest.',evidence:[observed('Guard observation','A person stands at the closed inner approach.'),response('Unarmed guard','A visible open-hand warning from a fixed standoff.')]},
   {id:'withdrawal',at:50,title:'The scripted intruder turns away',body:'The intruder turns and walks back along the exposed garden path. This is the scenario’s authored withdrawal, not an asserted effect of a sensor or a guaranteed deterrence result.',evidence:[observed('Garden passage','The person is moving away from the held inner approach.'),uncertain('The withdrawal is scripted; no forced-control capability is claimed.')]},
   {id:'outside',at:T.outside,title:'Back over the same boundary',body:'The intruder climbs back over the low wall with supported hands and feet, lands outside and departs. The camera retains the visible path only until the person leaves its illustrated sector.',evidence:[observed('Garden camera','A supported outward crossing and departure from the depicted coverage.'),response('Inner protection','The shutter and gate remain closed.')]},
  ]},
  {id:'resolve',at:T.resolve,title:'Record the outcome; finish the boundary check',body:'The record now shows the held occupied threshold and the visible departure. The guard approaches the crossing from inside to inspect it; the third record tile remains pending until that check is completed.',evidence:[observed('Event record','Inner protection stayed engaged and the scripted intruder withdrew.'),uncertain('Identity remains unestablished; the sequence does not establish that the entire property is safe.')],subevents:[{id:'boundary-inspected',at:T.inspected,title:'The guard completes the inside inspection',body:'The guard stops inside the crossed wall and looks over the coping. The third tile joins the console record. The intruder remains outside, the lights remain on, and the occupied threshold stays secured.',evidence:[observed('Guard inspection','The crossing is inspected from inside the estate.'),response('Completed record','Boundary check appended; inner protection remains engaged.'),uncertain('No identity or outcome beyond this illustrated event is established.')]}]},
 ],fallbackStills:[],
}
incident.fallbackStills=[{state:'establish',at:0,src:'/worlds/private-estate/intrusion-establish.webp',alt:incident.establishing.title+' Original illustrative incident.'},...incident.beats.flatMap(b=>[b,...(b.subevents||[])]).map(b=>({state:b.id,at:b.at,src:`/worlds/private-estate/intrusion-${b.id}.webp`,alt:b.title+' Original illustrative incident state.'}))]
export const definition:SceneDefinition={
 id:'private-estate',number:'01',name:'Private estate',subtitle:'The boundary holds',description:'An authored perimeter intrusion at an occupied woodland home. Corroborated observations, a human decision and visible protection — alongside an independent wildlife comparison.',setting:'Woodland residence · misty dawn',poster:incident.poster,posterAlt:incident.posterAlt,practicalLightLimit:3,
 palette:{background:'#bdcecf',fog:'#bdcecf',fogNear:21,fogFar:58,ambient:.36,sun:'#fff0d6',sunIntensity:1.4,sunPosition:[-12,22,14],hemisphereSky:'#d6e8f0',hemisphereGround:'#52604b',hemisphereIntensity:1.5,exposure:1.05,toneMapping:'aces',shadowBounds:{left:-24,right:24,top:22,bottom:-20,near:1,far:70,bias:-.00018,normalBias:.025,mapSize:2048}},defaultScenario:'intrusion',scenarios:[incident,wildlife],
}
