import type { SceneDefinition } from '../../contract'

/** A fictional yard sequence. Times are authored playback, not detection latency. */
export const definition: SceneDefinition = {
  id: 'logistics-yard', number: '05', name: 'Logistics yard',
  subtitle: 'Put movement in context',
  description: 'A loaded trailer enters the outbound lane. Ground observations and a requested aerial view add context while its release remains held.',
  lesson: 'Recognizing a vehicle is only the beginning. Its movement matters in the context of the yard’s expected releases.',
  establishing: {
    title: 'First light on the loading apron',
    body: 'The gantry prepares for another lift as a loaded tractor joins the outbound aisle. A proposed drone rests in its roof dock; no flight has been requested.',
  },
  setting: 'Intermodal yard · first light', duration: 66,
  poster: '/worlds/logistics-yard/poster.webp',
  posterAlt: 'An amber-lit intermodal yard with a braced gantry, container rows and a held tractor beside dispatch; a proposed drone rests in its roof dock.',
  palette: {
    background: '#d9c7b3', fog: '#d9c7b3', fogNear: 60, fogFar: 145,
    ambient: 0.13, sun: '#ffd8a7', sunIntensity: 3.8, sunPosition: [-38, 25, 32],
    hemisphereSky: '#c2d4e1', hemisphereGround: '#695642', hemisphereIntensity: 1.05,
    exposure: 1.04, toneMapping: 'aces',
    shadowBounds: { left: -51, right: 51, top: 39, bottom: -39, near: 1, far: 135, bias: -0.00015, normalBias: 0.035, mapSize: 2048 },
  },
  practicalLightLimit: 2,
  cameras: [
    { at: 0, position: [31, 8.6, 1.5], target: [23, 4.7, -7], mobilePosition: [29.2, 7.7, -.8], mobileTarget: [24.5, 4.6, -6.9], fov: 46, easing: 'smooth' },
    { at: 2, position: [0, 18, 26], target: [-17, 10, -10], mobilePosition: [-5, 16, 28], mobileTarget: [-18, 10, -10], fov: 46, cut: true, easing: 'smooth' },
    { at: 3.9, position: [0, 18, 26], target: [-17, 10, -10], mobilePosition: [-5, 16, 28], mobileTarget: [-18, 10, -10], fov: 46 },
    { at: 4, position: [-18.2, 7.7, 14], target: [-23.3, 5.3, 11], mobilePosition: [-19.3, 7.2, 13.7], mobileTarget: [-23.5, 5.3, 11.5], fov: 46, cut: true, easing: 'smoother' },
    { at: 6, position: [-18.2, 7.7, 14], target: [-23.3, 5.3, 11], mobilePosition: [-19.3, 7.2, 13.7], mobileTarget: [-23.5, 5.3, 11.5], fov: 46, easing: 'smoother' },
    { at: 8, position: [1, 6, 20], target: [-10, 2, -.5], mobilePosition: [0, 6.5, 21], mobileTarget: [-10, 2.4, -.5], fov: 43, easing: 'smooth' },
    { at: 10.9, position: [6, 6, 16], target: [-5, 2, 0], mobilePosition: [5, 7, 19], mobileTarget: [-5, 2.3, 0], fov: 43 },
    { at: 11, position: [-7.2, 7.7, -2.8], target: [-2.8, 4.8, 3.1], mobilePosition: [-6.1, 7, -2], mobileTarget: [-2.3, 5, 3.5], fov: 44, cut: true, easing: 'smoother' },
    { at: 13, position: [-7.2, 7.7, -2.8], target: [-2.8, 4.8, 3.1], mobilePosition: [-6.1, 7, -2], mobileTarget: [-2.3, 5, 3.5], fov: 44, easing: 'smoother' },
    { at: 16, position: [7, 8, 15], target: [0, 3, 1], mobilePosition: [6, 8, 17], mobileTarget: [0, 3, 1], fov: 43 },
    { at: 18, position: [29, 12, 22], target: [10, 2.3, -2.2], mobilePosition: [26, 11, 23], mobileTarget: [9.5, 2.6, -1], fov: 42, cut: true, easing: 'smoother' },
    { at: 26, position: [32, 11, 14], target: [22, 4.3, -5], mobilePosition: [30, 10.5, 13.5], mobileTarget: [22, 4.1, -5], fov: 44 },
    { at: 33.9, position: [32, 11, 14], target: [22, 4.3, -5], mobilePosition: [30, 10.5, 13.5], mobileTarget: [22, 4.1, -5], fov: 44 },
    { at: 34, position: [27, 8, 17], target: [14, 1.8, -2], mobilePosition: [27, 9, 20], mobileTarget: [14, 2, -1.5], fov: 42, cut: true },
    { at: 35.4, position: [27, 8, 17], target: [14, 1.8, -2], mobilePosition: [27, 9, 20], mobileTarget: [14, 2, -1.5], fov: 42 },
    { at: 35.5, position: [29.2, 11.6, -.9], target: [25.2, 8.9, -7.1], mobilePosition: [29.2, 11.1, -1.6], mobileTarget: [25.2, 8.9, -7.1], fov: 42, cut: true, easing: 'smoother' },
    { at: 40.4, position: [24, 12, -7], target: [20, 9.3, -13], mobilePosition: [24, 11.5, -7.5], mobileTarget: [20, 9.3, -13], fov: 42 },
    { at: 40.5, position: [25, 13, -20], target: [16, 5, -6], mobilePosition: [23.5, 12, -18.5], mobileTarget: [18.5, 7.5, -9], fov: 44, cut: true },
    { at: 46.5, position: [25, 13, -20], target: [16, 5, -6], mobilePosition: [23.5, 12, -18.5], mobileTarget: [18.5, 7.5, -9], fov: 44 },
    { at: 46.6, position: [24, 12, -7], target: [20, 9.3, -13], mobilePosition: [24, 11.5, -7.5], mobileTarget: [20, 9.3, -13], fov: 42, cut: true, easing: 'smoother' },
    { at: 52.4, position: [29.4, 11.6, -.9], target: [25.4, 8.9, -6.9], mobilePosition: [29.4, 11.1, -1.4], mobileTarget: [25.4, 8.9, -6.9], fov: 42 },
    { at: 52.5, position: [30, 9.5, 1], target: [25.4, 6.4, -6.9], mobilePosition: [30, 9.5, 1], mobileTarget: [25.4, 6.4, -6.9], fov: 44, cut: true, easing: 'smoother' },
    { at: 55, position: [30, 9.5, 1], target: [25.4, 6.4, -6.9], mobilePosition: [30, 9.5, 1], mobileTarget: [25.4, 6.4, -6.9], fov: 44, easing: 'smoother' },
    { at: 56, position: [29, 7, -2], target: [25.4, 5, -6.9], mobilePosition: [28.5, 7.3, -1.8], mobileTarget: [25.4, 4.9, -6.9], fov: 42 },
    { at: 60.5, position: [29, 7, -2], target: [25.4, 5, -6.9], mobilePosition: [28.5, 7.3, -1.8], mobileTarget: [25.4, 4.9, -6.9], fov: 42 },
    { at: 62, position: [36, 24, 30], target: [13, 3, -4], mobilePosition: [32, 20, 24], mobileTarget: [19, 4, -6], fov: 44, cut: true },
    { at: 66, position: [36, 24, 30], target: [13, 3, -4], mobilePosition: [32, 20, 24], mobileTarget: [19, 4, -6], fov: 44 },
  ],
  beats: [
    { id: 'detect', at: 4, title: 'A load leaves the row', body: 'A yard tractor carries a container toward the outbound apron. Movement is expected here; its release still needs context.', evidence: [{ source: 'Raised aisle camera', detail: 'A loaded trailer emerges from the cargo row.' }] },
    { id: 'verify', at: 11, title: 'Complementary views of the lane', body: 'The gantry briefly interrupts the camera view. The proposed system checks camera, radar and thermal observations on site to follow the same vehicle and load.', evidence: [{ source: 'Camera', detail: 'Aisle and apron views place the load on the outbound route.' }, { source: 'Radar', detail: 'A separate illustrated observation follows movement in the open lane.' }, { source: 'Proposed thermal head', detail: 'Body contrast adds context within its illustrated view; it does not identify the cargo.' }] },
    { id: 'correlate', at: 18, title: 'No matching release shown', body: 'The proposed local system checks that movement against the dispatch record. No matching release is shown, so the site team has an operational question to resolve.', evidence: [{ source: 'Dispatch movement record', detail: 'No release is linked to this outbound move.' }, { source: 'Linked observation', detail: 'The loaded tractor is approaching the verification bay.' }] },
    { id: 'decide', at: 26, title: 'Keep release held. Request another view.', body: 'The supervisor requests an aerial view of the cargo lane from the proposed drone while the site checks the movement record. More imagery cannot supply the missing release permission.', evidence: [{ source: 'Human review', detail: 'Aerial observation requested; release remains held.' }], action: 'Request aerial view; keep release held' },
    { id: 'respond', at: 34, title: 'A requested view of the held lane', body: 'Following the operator’s decision, the proposed drone observes the cargo lane and returns to its proposed dock. The supervisor continues the ground handoff. The vehicle waits and the outbound barrier stays closed.', evidence: [{ source: 'Proposed drone', detail: 'An operator-requested view adds lane context, never release permission.' }, { source: 'Site handoff', detail: 'The supervisor meets the held vehicle while the record check remains open.' }] },
    { id: 'resolve', at: 62, title: 'More context. Verification still open.', body: 'Ground observations, the requested aerial view and the supervisor’s hold decision remain linked in one illustrative record. The drone has returned; release still awaits the site’s record check.', evidence: [{ source: 'Ground observations', detail: 'Camera, radar and thermal context remain linked to the same illustrated movement.' }, { source: 'Dispatch', detail: 'Release still awaits site verification; the barrier stays closed.' }, { source: 'Proposed drone', detail: 'Requested lane observation retained; aircraft returned to its dock.' }] },
  ],
}
