import HeroWorld from '@/components/hero-world'
import { SiteHeader, SiteFooter, Mark } from '@/components/site-chrome'
import WorldExplorer from '@/components/worlds/explorer'

export default function Home() {
  return <><SiteHeader /><main id="main">
    <section className="hero section-width">
      <div className="hero-copy"><p className="eyebrow"><span className="status-dot" />A physical security concept</p><h1>Many signals.<br /><span>One clear<br className="desktop-break" /> picture.</span></h1><p className="hero-description">Tessure is designed to automatically connect and verify sensor observations on site, giving security teams one evidence-backed picture before a costly call.</p><div className="hero-actions"><a className="button primary" href="#worlds">Explore the worlds <span aria-hidden="true">↗</span></a><a className="text-link" href="#system">How it would work <span aria-hidden="true">↓</span></a></div><p className="hero-footnote">Local intelligence. Connected evidence. Human decisions.</p></div>
      <HeroWorld />
    </section>
    <section className="thesis section-width" aria-labelledby="thesis-heading"><p className="eyebrow">Why it matters</p><div className="thesis-layout"><h2 id="thesis-heading">A signal tells you<br />something happened.<br /><span>Context helps you<br />decide what comes next.</span></h2><div className="thesis-copy"><p>Separate systems raise separate alerts. People must piece them together and sort signal from noise. At sites where the consequences are high, a slow or wrong call can be costly.</p><p>Tessure proposes automatically correlating and checking camera, radar, thermal and site observations locally. The aim: one verified picture with supporting evidence, a person who decides what happens next, and a record of why. Here, verification means cross-checking observations; permission and the response still need site context and human review.</p><div className="signal-diagram" aria-label="Camera, radar and thermal observations converge into an event for human review"><div className="signal-inputs"><span>Camera</span><span>Radar</span><span>Thermal</span></div><div className="signal-converge" aria-hidden="true"><i /><i /><i /></div><div className="signal-event"><Mark /><span>One event</span></div><span className="signal-arrow" aria-hidden="true">→</span><div className="signal-human">Human<br />review</div></div></div></div></section>
    <section id="worlds" className="worlds-section" aria-labelledby="worlds-heading"><div className="section-width"><div className="section-intro"><div><p className="eyebrow">Explore the possibilities</p><h2 id="worlds-heading">Different places.<br /><span>Different decisions.</span></h2></div><p>Six worlds, built around the questions each site asks. Follow the observations, explore the evidence, and pause where a person makes the call.<small>These are authored illustrations of a proposed system. They do not demonstrate working detection software or measured performance.</small></p></div>
      <ol className="step-definitions" aria-label="Six steps in each illustration">
        <li><strong>Detect</strong><span>Notice activity that needs a closer look.</span></li>
        <li><strong>Verify</strong><span>Cross-check independent observations of the same activity.</span></li>
        <li><strong>Correlate</strong><span>Link the observations with site context and records.</span></li>
        <li><strong>Human review</strong><span>A person reviews the evidence and chooses a response.</span></li>
        <li><strong>Respond</strong><span>Show the response chosen by the person.</span></li>
        <li><strong>Record</strong><span>Record the outcome and any questions still open.</span></li>
      </ol>
      <WorldExplorer /></div></section>
    <section id="system" className="system-section" aria-labelledby="system-heading"><div className="section-width"><div className="section-intro"><div><p className="eyebrow">The system we're imagining</p><h2 id="system-heading">A layer of understanding.<br /><span>At the site.</span></h2></div><p>Designed to work with the cameras and security workflows a site already has. Complementary sensors would add context where it is needed.</p></div><div className="system-layout"><div className="node-study"><div className="node-label"><span>Fusion Node</span><span>Hardware concept</span></div><div className="node-drawing" aria-label="Illustrative Fusion Node enclosure with cooling fins and sensor connections" role="img"><div className="node-shadow" /><div className="node-case"><div className="node-fins">{Array.from({ length: 15 }, (_, i) => <i key={i} />)}</div><div className="node-face"><Mark /><span>tessure</span><i /></div><div className="node-ports"><i /><i /><i /><i /></div></div></div><p>An on-site appliance concept for bringing observations together locally.</p></div><div className="system-parts"><article><span>01 / Observe together</span><h3>Fusion Node</h3><p>Proposed on-site processing would automatically correlate and cross-check observations. Site records would add context, such as expected arrivals or cargo releases. Gaps and conflicting evidence would stay visible.</p></article><article><span>02 / Decide with context</span><h3>Command</h3><p>An operator would see the supporting observations, the remaining uncertainty and a suggested response. The decision stays with a person.</p></article><article><span>03 / Keep the reason</span><h3>Evidence</h3><p>The intended record links observations, the operator's decision and the resulting handoff. It preserves why an action was taken.</p></article></div></div><div className="design-principles"><div><span>Local by design</span><p>Process observations at the site. Make connection loss and sensor gaps visible.</p></div><div><span>Considered by design</span><p>Minimize unnecessary identity data. Give people a clear approval boundary.</p></div><div><span>Connected by design</span><p>Fit the systems a site uses. Preserve context when an event is handed over.</p></div></div></div></section>
    <section className="honesty section-width"><p className="eyebrow">Where the idea stands</p><div><h2>Designed here.<br /><span>Still to be proven<br />in the field.</span></h2><div><p>Tessure is a concept, not a deployed security product. These worlds explain the proposed approach.</p><p>Hardware, sensor integration, reliability, privacy controls and real-world performance still require engineering and field validation.</p><a className="text-link" href="https://github.com/fl-sean03/tessure/blob/main/specs/PRODUCT_ARCHITECTURE.md" target="_blank" rel="noreferrer">Read the original concept architecture ↗</a><small>A historical design document. Its specifications are proposals, not validated capabilities.</small></div></div></section>
    <section className="contact-section"><div className="section-width"><p className="eyebrow">A conversation worth having</p><h2>What would a clearer<br />picture change for your site?</h2><p className="contact-purpose">Get in touch with questions, feedback or thoughts on the Tessure concept.</p><a className="button light" href="mailto:sean.florez@colorado.edu">Share your thoughts <span aria-hidden="true">↗</span></a><p>sean.florez@colorado.edu</p></div></section>
  </main><SiteFooter /></>
}
